build_script:
  - cmd: dotnet build -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet test plist-cil.test\plist-cil.test.csproj

on_success:
  - cmd: dotnet pack plist-cil\plist-cil.csproj -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%

artifacts:
  - path: "plist-cil\\bin\\Release\\plist-cil.*.nupkg"